{
 "title": "E19e Gen II - Comparison view",
 "time": { "from": "2023-09-10T17:09:11.861Z", "to": "2023-09-13T02:30:33.216Z" },
 "templating": {
  "list": [
   {
    "name": "comparison_1_left",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_1_right",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_2_left",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_2_right",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_3_left",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_3_right",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_4_left",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_4_right",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_5_left",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   },
   {
    "name": "comparison_5_right",
    "label": "Select:",
    "query": "SELECT \"table_name\" as TNM\nFROM information_schema.tables \nWHERE table_schema = 'emex_gen2_7371';\n\n"
   }
  ]
 },
 "panels": [
  {
   "title": "Comparison #1 - LEFT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Comparison #1 - RIGHT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "Values comparison #1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_1_left:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n  \r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_1_left:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n  \r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_1_left:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);  \r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_1_right:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_1_right:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_1_right:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    }
   ]
  },
  {
   "title": "Comparison #2 - LEFT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 }
  },
  {
   "title": "Comparison #2 - RIGHT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Values comparison #2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_2_left:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_2_left:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_2_left:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_2_right:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_2_right:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_2_right:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    }
   ]
  },
  {
   "title": "Comparison #3 - LEFT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 24 }
  },
  {
   "title": "Comparison #3 - RIGHT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Values comparison #3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_3_left:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_3_left:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_3_left:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_3_right:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_3_right:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_3_right:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    }
   ]
  },
  {
   "title": "Comparison #4 - LEFT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 36 }
  },
  {
   "title": "Comparison #4 - RIGHT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Values comparison #4",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_4_left:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n  \r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_4_left:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_4_left:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_4_right:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_4_right:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_4_right:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    }
   ]
  },
  {
   "title": "Comparison #5 - LEFT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 48 }
  },
  {
   "title": "Comparison #5 - RIGHT axis",
   "type": "volkovlabs-variable-panel",
   "description": "Max 3 values can be displayed on this axis",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Values comparison #5",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_5_left:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_5_left:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_5_left:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_5_right:raw}', ',', 1) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_5_right:raw}', ',', 2) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    },
    {
     "rawSql": "SET\r\n  search_path TO emex_gen2_7371;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n\r\nDO $get_data$\r\nDECLARE\r\n  tbl_name text;\r\n  dyn_query text;\r\n\r\nBEGIN\r\n  SELECT SPLIT_PART('${comparison_5_right:raw}', ',', 3) into tbl_name;\r\n\r\n  dyn_query := format('CREATE TABLE temp_query_tbl AS SELECT $__timeGroupAlias(time_stamp,$__interval), max(%1$I) AS %1$I FROM %1$I\r\n  WHERE time_stamp BETWEEN ''${__from:date}'' AND ''${__to:date}'' GROUP BY 1 ORDER BY 1;', tbl_name, tbl_name, tbl_name);\r\n\r\n  EXECUTE dyn_query;\r\n\r\nEND $get_data$;\r\n\r\nSELECT * FROM temp_query_tbl;\r\n\r\nDROP TABLE IF EXISTS temp_query_tbl;\r\n"
    }
   ]
  }
 ]
}